name: mpoints_app
description: Enjoy for shopping to get more points from M-Points.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  http: ^1.0.0
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_secure_storage: ^8.1.0
  get: ^4.6.6
  json_annotation: ^4.8.1
  path: ^1.8.3
  sqflite: ^2.2.8+4
  intl: ^0.18.1
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.2
  qr_flutter: ^4.1.0
  barcode_widget: ^2.0.4
  skeletonizer: ^1.4.3
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.5

flutter_native_splash:
  color: "#13BFAA"
  color_dark: "#13BFAA"

  android_12:
    color: "#13BFAA"
    color_dark: "#13BFAA"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/touch-icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/icons/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
